### ISSUE TITLE
Menus have changed again - please keep this updated

### ISSUE THREAD

**Issue by pgferrero** [MicrosoftDocs/OfficeDocs-O365ITPro#246]
Unless this is just specific to me, I do not see the "Manage columns" options anymore.  If this is indeed removed from functionality, please update this page so it is relevant to the user.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b0edd827-38a3-12d1-7836-a2eacc97ed1c
* Version Independent ID: b0765177-6d47-49f4-47a5-2456107652c3
* Content: [Office 365 Reports in the Admin Center - Email activity](https://docs.microsoft.com/en-us/office365/admin/activity-reports/email-activity?view=o365-worldwide)
* Content Source: [Office365-Admin/activity-reports/email-activity.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/blob/public/Office365-Admin/activity-reports/email-activity.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by j0rt3g4** [comment]
This issue has been solved at pull [#242](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/pull/242)

**Comment by pgferrero** [comment]
Hi, maybe I don't get this seeing as this is my first post to this site.  I still see no "Manage columns" options in the Report, and the documentation has not changed - still had "Manage columns" as part of the documentation when it doesn't exist.  How is it solved?  Am I missing something?

**Comment by j0rt3g4** [comment]
Hi @pgferrero  the pull request is on there and it needs to be merged before you can actually see the changes. it will be on review for a few days before it gets approved and merged.

**Comment by pgferrero** [comment]
OK - wasn't sure what the process is here, and for the additional info - makes sense.

**Comment by j0rt3g4** [comment]
Solved at PR #261

**Comment by j0rt3g4** [comment]
@pgferrero  it's updated now 👍

**Comment by pgferrero** [comment]
Looks like what I see now.  Thanks!

**Comment by j0rt3g4** [comment]
Yep @pgferrero  thank you for reporting it

**Comment by mypil** [comment]
@AndreaBarr - This issue can be closed. Thank you.
